<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="HibernateTest" nsURI="http://org.eclipse.emf.cdo.tests.hibernate"
    nsPrefix="hibernatetests">
  <eClassifiers xsi:type="ecore:EClass" name="Bz356181_Main">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="transient" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="teneo.jpa">
        <details key="value" value="@Transient"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nonTransient" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transientRef" eType="#//Bz356181_Transient"
        transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transientOtherRef" eType="#//Bz356181_NonTransient"
        transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Bz356181_Transient">
    <eAnnotations source="teneo.jpa">
      <details key="value" value="@Transient"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Bz356181_NonTransient">
    <eStructuralFeatures xsi:type="ecore:EReference" name="main" eType="#//Bz356181_Main"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Bz387752_Main">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="strUnsettable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="def_value" unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="strSettable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="value"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="enumSettable" eType="#//Bz387752_Enum"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="enumUnsettable" eType="#//Bz387752_Enum"
        defaultValueLiteral="VAL1" unsettable="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Bz387752_Enum">
    <eLiterals name="VAL0"/>
    <eLiterals name="VAL1" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Bz380987_Group">
    <eStructuralFeatures xsi:type="ecore:EReference" name="people" upperBound="-1"
        eType="#//Bz380987_Person" eOpposite="#//Bz380987_Person/group"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Bz380987_Place">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="people" upperBound="-1"
        eType="#//Bz380987_Person" eOpposite="#//Bz380987_Person/places"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Bz380987_Person">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="group" upperBound="-1"
        eType="#//Bz380987_Group" eOpposite="#//Bz380987_Group/people"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="places" upperBound="-1"
        eType="#//Bz380987_Place" eOpposite="#//Bz380987_Place/people"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Bz398057A">
    <eAnnotations source="teneo.jpa">
      <details key="value" value="@Inheritance(strategy=InheritanceType.TABLE_PER_CLASS)"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="listOfB" upperBound="-1"
        eType="#//Bz398057B" containment="true" eOpposite="#//Bz398057B/refToClassA"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="teneo.jpa">
        <details key="value" value="@Id"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Bz398057A1" eSuperTypes="#//Bz398057A"/>
  <eClassifiers xsi:type="ecore:EClass" name="Bz398057B">
    <eAnnotations source="teneo.jpa">
      <details key="value" value="@Inheritance(strategy=InheritanceType.TABLE_PER_CLASS)"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="refToClassA" eType="#//Bz398057A"
        eOpposite="#//Bz398057A/listOfB"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="teneo.jpa">
        <details key="value" value="@Id"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Bz398057B1" eSuperTypes="#//Bz398057B">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="valueStr" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
