<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="modules" nsURI="http://www.eclipse.org/emf/CDO/lm/modules/1.0.0"
    nsPrefix="modules">
  <eClassifiers xsi:type="ecore:EClass" name="ModuleDefinition" eSuperTypes="../../org.eclipse.emf.cdo/model/etypes.ecore#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" lowerBound="1"
        eType="#//Version"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dependencies" upperBound="-1"
        eType="#//DependencyDefinition" containment="true" eOpposite="#//DependencyDefinition/source">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="dependency"/>
        <details key="kind" value="element"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DependencyDefinition" eSuperTypes="../../org.eclipse.emf.cdo/model/etypes.ecore#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//ModuleDefinition" eOpposite="#//ModuleDefinition/dependencies"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="targetName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="versionRange" lowerBound="1"
        eType="#//VersionRange"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Version" instanceClassName="org.eclipse.equinox.p2.metadata.Version"/>
  <eClassifiers xsi:type="ecore:EDataType" name="VersionRange" instanceClassName="org.eclipse.equinox.p2.metadata.VersionRange"/>
</ecore:EPackage>
