<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="model6" nsURI="http://www.eclipse.org/emf/CDO/tests/model6/1.0.0"
    nsPrefix="model6">
  <eClassifiers xsi:type="ecore:EClass" name="Root">
    <eStructuralFeatures xsi:type="ecore:EReference" name="listA" upperBound="-1"
        eType="#//BaseObject" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="listB" upperBound="-1"
        eType="#//BaseObject" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="listC" upperBound="-1"
        eType="#//BaseObject" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="listD" upperBound="-1"
        eType="#//BaseObject" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BaseObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="attributeOptional" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="attributeRequired" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="attributeList" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReferenceObject" eSuperTypes="#//BaseObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="referenceOptional" eType="#//BaseObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="referenceList" upperBound="-1"
        eType="#//BaseObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ContainmentObject" eSuperTypes="#//BaseObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="containmentOptional" eType="#//BaseObject"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="containmentList" upperBound="-1"
        eType="#//BaseObject" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UnorderedList">
    <eStructuralFeatures xsi:type="ecore:EReference" name="contained" ordered="false"
        upperBound="-1" eType="#//UnorderedList" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="referenced" ordered="false"
        upperBound="-1" eType="#//UnorderedList"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PropertiesMap">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="persistentMap" upperBound="-1"
        eType="#//PropertiesMapEntry" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transientMap" upperBound="-1"
        eType="#//PropertiesMapEntry" transient="true" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PropertiesMapEntry" instanceClassName="java.util.Map$Entry">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//PropertiesMapEntryValue"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PropertiesMapEntryValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="A">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedDs" upperBound="-1"
        eType="#//D" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedBs" upperBound="-1"
        eType="#//B" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="B">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedC" eType="#//C" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The style of the node."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="C"/>
  <eClassifiers xsi:type="ecore:EClass" name="D">
    <eStructuralFeatures xsi:type="ecore:EReference" name="data" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"
        containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="E">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedAs" upperBound="-1"
        eType="#//A" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="F">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedEs" upperBound="-1"
        eType="#//E" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="G">
    <eOperations name="isAttributeModified" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eOperations name="isReferenceModified" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eOperations name="isListModified" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dummy" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="reference" lowerBound="1"
        eType="#//BaseObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="list" upperBound="-1" eType="#//BaseObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="MyEnum">
    <eLiterals name="ZERO"/>
    <eLiterals name="ONE" value="1"/>
    <eLiterals name="TWO" value="2"/>
    <eLiterals name="THREE" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MyEnumList">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="myEnum" upperBound="-1"
        eType="#//MyEnum"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MyEnumListUnsettable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="myEnum" upperBound="-1"
        eType="#//MyEnum" unsettable="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Holder" eSuperTypes="#//Holdable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="held" upperBound="-1" eType="#//Holdable"
        transient="true" derived="true">
      <eAnnotations source="http://www.eclipse.org/emf/CDO">
        <details key="persistent" value="true"/>
        <details key="filter" value="owned"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="owned" upperBound="-1"
        eType="#//Holdable" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Thing" eSuperTypes="#//Holdable"/>
  <eClassifiers xsi:type="ecore:EClass" name="Holdable" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HasNillableAttribute">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nillable" eType="#//MyString"
        unsettable="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="MyString" instanceClassName="java.lang.String"/>
  <eClassifiers xsi:type="ecore:EClass" name="EmptyStringDefault">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="attribute" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EmptyStringDefaultUnsettable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="attribute" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="" unsettable="true"/>
  </eClassifiers>
</ecore:EPackage>
