<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="net4jutildefs"
    nsURI="http://www.eclipse.org/NET4J/util/defs/1.0.0" nsPrefix="net4jutildefs">
  <eClassifiers xsi:type="ecore:EClass" name="DefsContainer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="definitions" lowerBound="1"
        upperBound="-1" eType="#//Def" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="defaultDefinition" eType="#//Def"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Def" abstract="true">
    <eOperations name="getInstance" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    <eOperations name="unsetInstance"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExecutorServiceDef" abstract="true"
      eSuperTypes="#//Def"/>
  <eClassifiers xsi:type="ecore:EClass" name="ThreadPoolDef" eSuperTypes="#//ExecutorServiceDef"/>
</ecore:EPackage>
