/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.eclipse.emf.cdo.eresource.validation;

import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.common.util.URI;

import org.eclipse.emf.ecore.EObject;

import org.eclipse.emf.ecore.resource.Resource.Diagnostic;

import org.eclipse.emf.ecore.resource.ResourceSet;

/**
 * A sample validator interface for
 * {@link org.eclipse.emf.cdo.eresource.CDOResource}. This doesn't really do
 * anything, and it's not a real EMF artifact. It was generated by the
 * org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's
 * code generator can be extended. This can be disabled with -vmargs
 * -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CDOResourceValidator
{
  boolean validate();

  boolean validateResourceSet(ResourceSet value);

  boolean validateURI(URI value);

  boolean validateContents(EList<EObject> value);

  boolean validateModified(boolean value);

  boolean validateLoaded(boolean value);

  boolean validateTrackingModification(boolean value);

  boolean validateErrors(EList<Diagnostic> value);

  boolean validateWarnings(EList<Diagnostic> value);

  boolean validatePath(String value);
}
