/**
 * <copyright>
 * </copyright>
 *
 * $Id: CDOResourceFolderValidator.java,v 1.1 2008-12-29 14:53:09 estepper Exp $
 */
package org.eclipse.emf.cdo.eresource.validation;

import org.eclipse.emf.cdo.eresource.CDOResourceNode;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link org.eclipse.emf.cdo.eresource.CDOResourceFolder}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CDOResourceFolderValidator
{
  boolean validate();

  boolean validateNodes(EList<CDOResourceNode> value);
}
