/**
 * <copyright>
 * </copyright>
 *
 * $Id: CDOResourceNodeValidator.java,v 1.1 2008-12-29 14:53:09 estepper Exp $
 */
package org.eclipse.emf.cdo.eresource.validation;

import org.eclipse.emf.cdo.eresource.CDOResourceFolder;

/**
 * A sample validator interface for {@link org.eclipse.emf.cdo.eresource.CDOResourceNode}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CDOResourceNodeValidator
{
  boolean validate();

  boolean validateFolder(CDOResourceFolder value);

  boolean validateName(String value);

  boolean validatePath(String value);
}
