/**
 * <copyright>
 * </copyright>
 *
 * $Id: CDOResourceDefValidator.java,v 1.1 2008-12-29 14:01:20 estepper Exp $
 */
package org.eclipse.emf.cdo.cdodefs.validation;

import org.eclipse.emf.cdo.cdodefs.CDOTransactionDef;
import org.eclipse.emf.cdo.cdodefs.ResourceMode;

/**
 * A sample validator interface for {@link org.eclipse.emf.cdo.cdodefs.CDOResourceDef}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CDOResourceDefValidator
{
  boolean validate();

  boolean validateCdoTransaction(CDOTransactionDef value);
  boolean validateResourceMode(ResourceMode value);
  boolean validatePath(String value);
}
