<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="model5" nsURI="http://www.eclipse.org/emf/CDO/tests/model5/1.0.0"
    nsPrefix="model5">
  <eClassifiers xsi:type="ecore:EClass" name="Manager"/>
  <eClassifiers xsi:type="ecore:EClass" name="Doctor"/>
  <eClassifiers xsi:type="ecore:EClass" name="GenListOfString">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="elements" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GenListOfInt">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="elements" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GenListOfInteger">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="elements" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GenListOfLong">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="elements" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GenListOfBoolean">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="elements" unique="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GenListOfShort">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="elements" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EShort"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GenListOfFloat">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="elements" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GenListOfDouble">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="elements" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GenListOfDate">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="elements" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GenListOfChar">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="elements" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EChar"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GenListOfIntArray">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="elements" upperBound="-1"
        eType="#//IntArray"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="IntArray" instanceClassName="int[]"/>
  <eClassifiers xsi:type="ecore:EClass" name="Parent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//Child" containment="true" eOpposite="#//Child/parent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="favourite" eType="#//Child"
        eOpposite="#//Child/preferredBy"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Child">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//Parent"
        eOpposite="#//Parent/children"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="preferredBy" eType="#//Parent"
        eOpposite="#//Parent/favourite"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WithCustomType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="#//CustomType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="CustomType" instanceClassName="org.eclipse.emf.cdo.tests.model5.CustomType"/>
</ecore:EPackage>
