<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="projectconfig" nsURI="http://www.eclipse.org/CDO/releng/projectconfig/1.0"
    nsPrefix="projectconfig">
  <eClassifiers xsi:type="ecore:EClass" name="WorkspaceConfiguration">
    <eOperations name="applyPreferenceProfiles"/>
    <eOperations name="updatePreferenceProfileReferences"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="propertyFilters" upperBound="-1"
        eType="#//PropertyFilter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="projects" upperBound="-1"
        eType="#//Project" containment="true" eOpposite="#//Project/configuration"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="defaultPreferenceNode"
        lowerBound="1" eType="ecore:EClass ../../org.eclipse.emf.cdo.releng.preferences/model/preferences.ecore#//PreferenceNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="instancePreferenceNode"
        lowerBound="1" eType="ecore:EClass ../../org.eclipse.emf.cdo.releng.preferences/model/preferences.ecore#//PreferenceNode"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Project">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="AllPreferencesManaged"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="configuration" lowerBound="1"
        eType="#//WorkspaceConfiguration" eOpposite="#//WorkspaceConfiguration/projects"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="preferenceProfiles" upperBound="-1"
        eType="#//PreferenceProfile" containment="true" eOpposite="#//PreferenceProfile/project"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="preferenceNode" lowerBound="1"
        eType="ecore:EClass ../../org.eclipse.emf.cdo.releng.preferences/model/preferences.ecore#//PreferenceNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="preferenceProfileReferences"
        upperBound="-1" eType="#//PreferenceProfile" eOpposite="#//PreferenceProfile/referentProjects"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PreferenceProfile">
    <eOperations name="requires" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="preferenceProfile" eType="#//PreferenceProfile"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="preferenceFilters" upperBound="-1"
        eType="#//PreferenceFilter" containment="true" eOpposite="#//PreferenceFilter/preferenceProfile"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="referentProjects" upperBound="-1"
        eType="#//Project" eOpposite="#//Project/preferenceProfileReferences"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="project" eType="#//Project"
        eOpposite="#//Project/preferenceProfiles"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="predicates" upperBound="-1"
        eType="ecore:EClass ../../org.eclipse.emf.cdo.releng.predicates/model/predicates.ecore#//Predicate"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="prerequisites" upperBound="-1"
        eType="#//PreferenceProfile"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PreferenceFilter">
    <eOperations name="matches" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="preferenceNode" lowerBound="1"
        eType="ecore:EClass ../../org.eclipse.emf.cdo.releng.preferences/model/preferences.ecore#//PreferenceNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="preferenceProfile" lowerBound="1"
        eType="#//PreferenceProfile" eOpposite="#//PreferenceProfile/preferenceFilters"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="inclusions" lowerBound="1"
        eType="#//Pattern" defaultValueLiteral=".*"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="exclusions" lowerBound="1"
        eType="#//Pattern" defaultValueLiteral=""/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Pattern" instanceClassName="java.util.regex.Pattern"/>
  <eClassifiers xsi:type="ecore:EClass" name="PropertyFilter">
    <eOperations name="matches" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="omissions" lowerBound="1"
        eType="#//Pattern"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="predicates" upperBound="-1"
        eType="ecore:EClass ../../org.eclipse.emf.cdo.releng.predicates/model/predicates.ecore#//Predicate"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
