/**
 * <copyright>
 * </copyright>
 *
 * $Id: TestDefValidator.java,v 1.1 2008-12-30 08:43:08 estepper Exp $
 */
package org.eclipse.net4j.util.tests.defs.validation;

import org.eclipse.net4j.util.net4jutildefs.Def;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link org.eclipse.net4j.util.tests.defs.TestDef}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TestDefValidator
{
  boolean validate();

  boolean validateReferences(EList<Def> value);
  boolean validateAttribute(String value);
}
