/**
 * <copyright>
 * </copyright>
 *
 * $Id: OrderAddressValidator.java,v 1.2 2009-01-10 13:55:59 estepper Exp $
 */
package org.eclipse.emf.cdo.tests.model1.validation;

/**
 * A sample validator interface for {@link org.eclipse.emf.cdo.tests.model1.OrderAddress}. This doesn't really do
 * anything, and it's not a real EMF artifact. It was generated by the org.eclipse.emf.examples.generator.validator
 * plug-in to illustrate how EMF's code generator can be extended. This can be disabled with -vmargs
 * -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface OrderAddressValidator
{
  boolean validate();

  boolean validateTestAttribute(boolean value);
}
