/**
 * <copyright>
 * </copyright>
 *
 * $Id: Product1Validator.java,v 1.2 2009-01-10 13:55:59 estepper Exp $
 */
package org.eclipse.emf.cdo.tests.model1.validation;

import org.eclipse.emf.cdo.tests.model1.OrderDetail;
import org.eclipse.emf.cdo.tests.model1.VAT;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link org.eclipse.emf.cdo.tests.model1.Product1}. This doesn't really do anything,
 * and it's not a real EMF artifact. It was generated by the org.eclipse.emf.examples.generator.validator plug-in to
 * illustrate how EMF's code generator can be extended. This can be disabled with -vmargs
 * -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface Product1Validator
{
  boolean validate();

  boolean validateName(String value);

  boolean validateOrderDetails(EList<OrderDetail> value);

  boolean validateVat(VAT value);

  boolean validateDescription(String value);
}
