/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.eclipse.emf.cdo.tests.model1.validation;

import org.eclipse.emf.cdo.tests.model1.Customer;

/**
 * A sample validator interface for {@link org.eclipse.emf.cdo.tests.model1.SalesOrder}. This doesn't really do
 * anything, and it's not a real EMF artifact. It was generated by the org.eclipse.emf.examples.generator.validator
 * plug-in to illustrate how EMF's code generator can be extended. This can be disabled with -vmargs
 * -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SalesOrderValidator
{
  boolean validate();

  boolean validateId(int value);

  boolean validateCustomer(Customer value);
}
