<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="defs"
    nsURI="http://www.eclipse.org/NET4J/defs/tests/1.0.0" nsPrefix="net4j.defs.tests">
  <eClassifiers xsi:type="ecore:EClass" name="TestDef" eSuperTypes="../../org.eclipse.net4j.util.defs/model/org.eclipse.net4j.util.defs.ecore#//Def">
    <eStructuralFeatures xsi:type="ecore:EReference" name="references" upperBound="-1"
        eType="ecore:EClass ../../org.eclipse.net4j.util.defs/model/org.eclipse.net4j.util.defs.ecore#//Def"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="attribute" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
