<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="assembly" nsURI="http://www.eclipse.org/emf/CDO/lm/assembly/1.0.0"
	nsPrefix="assembly">
	<eClassifiers xsi:type="ecore:EClass" name="Assembly" eSuperTypes="../../org.eclipse.emf.cdo/model/etypes.ecore#//ModelElement">
		<eStructuralFeatures xsi:type="ecore:EAttribute" name="systemName" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" />
		<eStructuralFeatures xsi:type="ecore:EReference" name="modules" upperBound="-1" eType="#//AssemblyModule" containment="true" eOpposite="#//AssemblyModule/assembly">
			<eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
				<details key="name" value="module" />
				<details key="kind" value="element" />
			</eAnnotations>
		</eStructuralFeatures>
	</eClassifiers>
	<eClassifiers xsi:type="ecore:EClass" name="AssemblyModule" eSuperTypes="../../org.eclipse.emf.cdo/model/etypes.ecore#//ModelElement">
		<eStructuralFeatures xsi:type="ecore:EReference" name="assembly" lowerBound="1" eType="#//Assembly" eOpposite="#//Assembly/modules" />
		<eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" />
		<eStructuralFeatures xsi:type="ecore:EAttribute" name="version" lowerBound="1" eType="ecore:EDataType ../../org.eclipse.emf.cdo.lm.modules/model/Modules.ecore#//Version" />
		<eStructuralFeatures xsi:type="ecore:EAttribute" name="branchPoint" lowerBound="1" eType="ecore:EDataType ../../org.eclipse.emf.cdo/model/etypes.ecore#//BranchPointRef" />
		<eStructuralFeatures xsi:type="ecore:EAttribute" name="root" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean" />
	</eClassifiers>
</ecore:EPackage>
