<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="testmodel1"
    nsURI="http://www.eclipse.org/emf/cdo/2006/TestModel1" nsPrefix="testmodel1">
  <eClassifiers xsi:type="ecore:EClass" name="TreeNode" eSuperTypes="../../org.eclipse.emf.cdo.client/model/client.ecore#//CDOPersistent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//TreeNode"
        eOpposite="#//TreeNode/children"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//TreeNode" containment="true" eOpposite="#//TreeNode/parent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent2" eType="#//TreeNode"
        eOpposite="#//TreeNode/children2"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="children2" upperBound="-1"
        eType="#//TreeNode" containment="true" eOpposite="#//TreeNode/parent2"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="references" upperBound="-1"
        eType="#//TreeNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="reference" eType="#//TreeNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceRef" eType="#//TreeNode"
        eOpposite="#//TreeNode/targetRef"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetRef" eType="#//TreeNode"
        eOpposite="#//TreeNode/sourceRef"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="booleanFeature" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="intFeature" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stringFeature" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExtendedNode" eSuperTypes="#//TreeNode">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bidiSource" upperBound="-1"
        eType="#//ExtendedNode" eOpposite="#//ExtendedNode/bidiTarget"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bidiTarget" upperBound="-1"
        eType="#//ExtendedNode" eOpposite="#//ExtendedNode/bidiSource"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stringFeature2" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EmptyNode" eSuperTypes="#//TreeNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="EmptyRefNode" eSuperTypes="#//TreeNode">
    <eStructuralFeatures xsi:type="ecore:EReference" name="moreReferences" upperBound="-1"
        eType="#//TreeNode"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Root" eSuperTypes="../../org.eclipse.emf.cdo.client/model/client.ecore#//CDOPersistent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="ecore:EClass ../../org.eclipse.emf.cdo.client/model/client.ecore#//CDOPersistent"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Author" eSuperTypes="../../org.eclipse.emf.cdo.client/model/client.ecore#//CDOPersistent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="books" upperBound="-1"
        eType="#//Book" eOpposite="#//Book/author"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Book" eSuperTypes="../../org.eclipse.emf.cdo.client/model/client.ecore#//CDOPersistent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="author" eType="#//Author"
        eOpposite="#//Author/books"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
