<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="model3"
    nsURI="http://www.eclipse.org/emf/CDO/tests/model3/1.0.0" nsPrefix="model3">
  <eClassifiers xsi:type="ecore:EClass" name="Class1">
    <eStructuralFeatures xsi:type="ecore:EReference" name="class2" upperBound="-1"
        eType="#//subpackage/Class2" unsettable="true" eOpposite="#//subpackage/Class2/class1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MetaRef">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ePackageRef" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EPackage"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Point" instanceClassName="org.eclipse.emf.cdo.tests.model3.Point"/>
  <eClassifiers xsi:type="ecore:EClass" name="Polygon">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Point" lowerBound="1" upperBound="-1"
        eType="#//Point"/>
  </eClassifiers>
  <eSubpackages name="subpackage" nsURI="http://www.eclipse.org/emf/CDO/tests/subpackage/1.0.0"
      nsPrefix="subpackage">
    <eClassifiers xsi:type="ecore:EClass" name="Class2">
      <eStructuralFeatures xsi:type="ecore:EReference" name="class1" upperBound="-1"
          eType="#//Class1" eOpposite="#//Class1/class2"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
